name: Deploy Bonobot
on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Build and deploy Bonobot.
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.0

    - name: Create ssh private key file from env var
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        set -ex
        sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > id_ed25519_testing
        chmod 400 id_ed25519_testing
        
    - name: Connect via SSH to server
      run: |
        # TODO: connect to ssh, pull changes (since action runs when pushed to master), build image, remove prevoius container and run container with the newly created image.
        # ssh -i id_ed25519_testing ${{ secrets.SERVER }} -f 
